{
 "title": "Timings",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "scan_response.timings.clamav_scan_us",
       "id": "1",
       "type": "avg"
      },
      {
       "field": "scan_response.timings.buffer_us",
       "id": "3",
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "scan_response.timings.clamav_scan_us",
       "id": "1",
       "type": "max"
      },
      {
       "field": "scan_response.timings.buffer_us",
       "id": "3",
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Scan Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}