{
 "title": "(master) samarths - tcfa",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "File Counts - Past 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Detection Distribution (Top 15) - Past 24 Hours",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "scan_response.timings.clamav_scan_us",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1d", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[check unit] File Sizes - Past 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "scan_result.metadata.size", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Type Distribution (Top 15) - Past 24 Hours",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "scan_result.metadata.filetype",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1d", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Sha256 Distribution (Top 15) - Past 24 Hours",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "scan_result.metadata.member_hashes.sha2-256",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Detection/Conviction Counts (Top 15) - Past 24 Hours",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 11, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "scan_result.verdict.Matches",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Detection/Conviction Counts - Past 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "scan_result.verdict.Matches:\"SUBMIT.HTML\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "scan_result.verdict.Matches:* AND NOT scan_result.verdict.Matches:\"SUBMIT.HTML\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Detection/Conviction Distribution - Past 24 Hours",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "scan_result.verdict.Matches", "id": "3", "settings": { "order": "desc", "orderBy": "1", "size": "0" }, "type": "terms" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "scan_result.verdict.Matches:\"SUBMIT.HTML\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "scan_result.verdict.Matches", "id": "2", "settings": { "order": "desc", "orderBy": "1", "size": "0" }, "type": "terms" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "scan_result.verdict.Matches:* AND NOT scan_result.verdict.Matches:\"SUBMIT.HTML\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Scan Times (Buffer + Scan) - Past 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "scan_response.timings.clamav_scan_us",
       "id": "1",
       "type": "avg"
      },
      {
       "field": "scan_response.timings.buffer_us",
       "id": "3",
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}