{
 "title": "Daily Import Counts and Sizes",
 "time": { "from": "now-15d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Server",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\"}"
   },
   {
    "name": "feed",
    "label": "Feed",
    "query": "{\"find\": \"terms\", \"field\": \"tag\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "New Samples Imported Daily",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>50000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>100000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>200000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:300000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>400000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>500000000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicate Samples Processed Daily",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$feed",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Total Samples Processed Daily",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND fields.logtype:\"import\" AND tag:$feed",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Total Sample Size Imported Daily (Compressed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed ",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>200000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>300000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>400000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>500000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>100000000",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND raw_file_size:>500000000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Total Sample Size Imported Daily (Uncompressed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "raw_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Average Raw Sample Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "raw_file_size", "id": "1", "settings": { "script": "_value / (1024*1024)" }, "type": "avg" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}