{
 "title": "Samples Per Day By Feed",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mimetype",
    "label": "mimetype",
    "query": "{\"find\": \"terms\", \"field\": \"mime_type.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "All Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "VT Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:vt AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:vt AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Reversing Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:reversinglabs AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:reversinglabs AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Cymru Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:cymru AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:cymru AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Threatgrid Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:threatgrid AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:threatgrid AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Sintelligence Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag: sintelligence AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag: sintelligence AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Ikarus Samples / Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:ikarus AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:ikarus AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "RTTI Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:rtti AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "alias": "new",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:rtti AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "VRT Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:vrt AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:vrt AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Cisco Corpus Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:cisco-corpus AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:cisco-corpus AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Ahnlab Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:ahnlab AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:ahnlab AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "BFK Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:bfk AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:bfk AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Web Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:web AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:web AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Sunbelt Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:sunbelt AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:sunbelt AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Systweak Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:systweak AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:systweak AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Avira Samples / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:avira AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:avira AND is_dupe:\"N\" AND mime_type.keyword:$mimetype",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}