{
 "title": "VRT Imports by Server / last hour",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tagname",
    "label": "Feed",
    "query": "{\"find\": \"terms\", \"field\": \"tag\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "New Samples Last Hour ifeeds01",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds01.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds01",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds01.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour ifeeds02",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds02.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds02",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds02.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour ifeeds03",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds03.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds03",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds03.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour ifeeds04",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds04.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds04",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds04.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour ifeeds05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds05.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds05.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour ifeeds06",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds06.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds06",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds06.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour ifeeds10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds10.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour ifeeds10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"ifeeds10.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Last Hour search01",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"search01.vrt.sourcefire.com\" AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Last Hour search01",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:\"search01.vrt.sourcefire.com\" AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}