{
 "title": "VRT Imports",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Server",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\"}"
   },
   {
    "name": "tagname",
    "label": "Feed",
    "query": "{\"find\": \"terms\", \"field\": \"tag\"}"
   },
   {
    "name": "duplicate",
    "label": "Duplicate?",
    "query": "{\"find\": \"terms\", \"field\": \"is_dupe\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "New Samples Processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\" AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Samples per Host",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:$duplicate AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicate Samples Processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "New Samples Processed per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Sample Age (Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sample_age",
       "id": "1",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "avg"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:$duplicate AND fields.logtype:\"import\" AND tag:$tagname AND sample_age:<10000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Duplicates Processed per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"Y\"AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Sample Process Time (sec) (New Samples)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "process_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:$duplicate AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    },
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "check_sample_time",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "check_sid_time",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "nfs_move_time",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "handle_dupe_time",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "raw_copy_time",
       "id": "7",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:$duplicate AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Sample Raw Size (Avg) (New Samples)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "raw_file_size",
       "id": "3",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:$duplicate AND fields.logtype:\"import\" AND tag:$tagname",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}