{
 "title": "Daily Import Large Files - Compressed Zoo6 (Q2FY24)",
 "time": { "from": "2023-07-27T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Server",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\"}"
   },
   {
    "name": "feed",
    "label": "Feed",
    "query": "{\"find\": \"terms\", \"field\": \"tag\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily Sample >200MB, by Source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tag",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "hide": false,
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND compressed_file_size:>50000000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Daily Import Large Sample Size Sliced (Compressed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": ">50MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>50000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">100MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>100000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">200MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>200000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">300MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>300000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">400MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>400000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">500MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>500000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">600MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "compressed_file_size",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "missing": 0, "script": { "inline": "_value / (1024*1024)" } },
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>600000000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Daily Import Large Sample Count Sliced (Compressed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": ">50MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=50000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">100MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=100000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">200MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=200000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">300MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=300000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">400MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=400000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">500MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=500000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": ">600MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=600000000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Daily Import Large Sample Size Bands (Compressed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "50-100MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=50000000 AND compressed_file_size:<100000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "100-200MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=100000000 AND compressed_file_size:<200000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "200-300MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=200000000 AND compressed_file_size:<300000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "300-400MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=300000000 AND compressed_file_size:<400000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "400-500MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=400000000 AND compressed_file_size:<500000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "500-600MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=500000000 AND compressed_file_size:<600000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "600MB+",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "compressed_file_size", "id": "1", "type": "sum" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=600000000",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Daily Import Large Sample Count Bands (Compressed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "50-100MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=50000000 AND compressed_file_size:<100000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "100-200MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=100000000 AND compressed_file_size:<200000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "200-300MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=200000000 AND compressed_file_size:<300000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "300-400MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=300000000 AND compressed_file_size:<400000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "400-500MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=400000000 AND compressed_file_size:<500000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "500-600MB",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=500000000 AND compressed_file_size:<600000000",
     "timeField": "import_timestamp"
    },
    {
     "alias": "600MB+",
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host.name:$hostname AND is_dupe:\"N\"AND fields.logtype:\"import\" AND tag:$feed AND compressed_file_size:>=600000000",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}