{
 "title": "Signatures",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Number of Signatures Created",
   "type": "graph",
   "description": "Number of ClamAV Signatures Created by mAGIC",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n $__timeGroupAlias(timestamp,'5m'),\n count(id) AS \"signatures_count\"\nFROM core_signature \nWHERE\n  $__timeFilter(timestamp)\nGROUP BY time\nORDER BY time",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Number of Signatures Verified",
   "type": "graph",
   "description": "Number of ClamAV Signatures Verified by mAGIC and passed along to Sig Manager for publishing. \n\nDo not use this for reporting as it might change as Signatures being dropped in future due to FP in Wild.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n $__timeGroupAlias(core_clamsignature.timestamp_fp_test_last_changed ,'5m'),\n count(core_signature.id) AS \"Verified_signatures_count\"\nFROM core_signature \n\tINNER JOIN core_clamsignature ON (core_signature.sig_id = core_clamsignature.id) \nWHERE (core_signature.duplicate = False \n\tAND core_clamsignature.status_burn_in IN (4, 11) \n\tAND core_clamsignature.status_fp_test IN (4, 11)\n\tAND $__timeFilter(core_clamsignature.timestamp_fp_test_last_changed))\nGROUP BY time\nORDER BY time",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Number of  Wild FP Signatures.",
   "type": "graph",
   "description": "FPs in the wild by observing the stream of VT reports",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT  $__timeGroupAlias(core_clamsignature.timestamp_fp_test_last_changed ,'5m'), Count(periodic_wildfp.sig_id) AS wildfp_sig_count\nFROM dashboard.periodic_wildfp   \n    INNER JOIN dashboard.core_clamsignature ON  (periodic_wildfp.sig_id  = core_clamsignature.id)     \nWHERE core_clamsignature.status_fp_test IN (12,13)\n\tAND $__timeFilter(core_clamsignature.timestamp_fp_test_last_changed)\nGROUP BY time\nORDER BY time",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}