{
 "title": "Submissions",
 "description": "Everything about Submissions to mAGIC",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "submitter",
    "query": "select DISTINCT(submitter) From core_submission"
   }
  ]
 },
 "panels": [
  {
   "title": "Submissions By each Submitter (Stacked Bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(submitted,'10m') AS \"time\",\n  submitter AS metric,\n  count(id) AS \"value\"\nFROM core_submission\nWHERE\n  $__timeFilter(submitted)\nGROUP BY time, submitter\nORDER BY time",
     "timeField": "import_timestamp"
    }
   ]
  },
  {
   "title": "Submissions By each Submitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(submitted) DIV 300 * 300 AS \"time\",\n  submitter AS metric,\n  count(id) AS \"value\"\nFROM core_submission\nWHERE\n  $__timeFilter(submitted)\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Number of Submissions",
   "type": "graph",
   "description": "Number of Submissions  made to mAGIC for  generating ClamAV Signatures.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "import_timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n $__timeGroupAlias(submitted,'5m'),\n count(id) AS \"submissions_made\"\nFROM core_submission \nWHERE\n  $__timeFilter(submitted) AND submitter IN ($submitter)\nGROUP BY time\nORDER BY time\n\n",
     "timeField": "import_timestamp"
    }
   ]
  }
 ]
}