{
 "title": "IPAS Core Distribution",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RuleName",
    "label": "Rule Name",
    "query": "{\"find\": \"terms\", \"field\": \"rule_name.keyword\"}"
   },
   {
    "name": "Provider",
    "label": "Provider",
    "query": "{\"find\": \"terms\", \"field\": \"provider\"}\t"
   }
  ]
 },
 "panels": [
  {
   "title": "Hit%",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "hits_percent", "id": "1", "type": "avg" }
     ],
     "query": "rule_name.keyword:$RuleName AND provider:$Provider",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rule Score",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "score_avg", "id": "1", "type": "avg" }
     ],
     "query": "rule_name.keyword:$RuleName AND provider:$Provider",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hit% Focused",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "hits_percent",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "provider:$Provider AND rule_name.keyword:$RuleName",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Effect",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "total_effects", "id": "1", "type": "sum" }
     ],
     "query": "rule_name.keyword:$RuleName AND provider:$Provider AND score:[0 TO 100000000000]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}