{
 "title": "SBNP dashbord",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RuleName",
    "label": "Rule Name",
    "query": "{\"find\": \"terms\", \"field\": \"rule_name.keyword\"}"
   },
   {
    "name": "Provider",
    "label": "Provider",
    "query": "{\"find\": \"terms\", \"field\": \"provider\"}\t"
   }
  ]
 },
 "panels": [
  {
   "title": "SBNP volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_messages", "id": "1", "type": "max" },
      { "field": "total_effects", "id": "3", "type": "sum" }
     ],
     "query": "provider:$Provider AND score:[0 TO 100000000000]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IPAS Verdicts over time, MSG%",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "histogram.0_10",
       "id": "1",
       "settings": {
        "script": "_value + doc[\"histogram.20_30\"].value + doc[\"histogram.30_40\"].value + doc[\"histogram.40_50\"].value"
       },
       "type": "avg"
      },
      {
       "field": "histogram.50_60",
       "id": "3",
       "settings": {
        "script": "_value + doc[\"histogram.60_70\"].value + doc[\"histogram.70_80\"].value + doc[\"histogram.80_90\"].value"
       },
       "type": "avg"
      },
      { "field": "histogram.90_100", "id": "4", "type": "avg" }
     ],
     "query": "provider:$Provider",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IPAS Verdicts over time, MSG",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "histogram.0_10",
       "id": "1",
       "settings": {
        "script": "_value + doc[\"histogram.10_20\"].value + doc[\"histogram.20_30\"].value + doc[\"histogram.30_40\"].value + doc[\"histogram.40_50\"].value"
       },
       "type": "avg"
      },
      {
       "field": "histogram.50_60",
       "id": "3",
       "settings": {
        "script": "_value + doc[\"histogram.60_70\"].value + doc[\"histogram.70_80\"].value + doc[\"histogram.80_90\"].value"
       },
       "type": "avg"
      },
      { "field": "histogram.90_100", "id": "4", "type": "avg" }
     ],
     "query": "provider:$Provider",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rule Hits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hits", "id": "1", "settings": { "missing": "0" }, "type": "avg" }
     ],
     "query": "provider:$Provider AND rule_name.keyword:$RuleName",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}